# CMake generated Testfile for 
# Source directory: C:/D/PBE/PlusLib/src/PlusCommon/Testing
# Build directory: C:/D/PBE/PlusLib-bin/src/PlusCommon/Testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(vtkPlusLoggerTest "C:/D/PBE/bin/vtkPlusLoggerTest" "--verbose=5")
add_test(PlusCommonTest "C:/D/PBE/bin/PlusCommonTest")
add_test(PlusMathTest "C:/D/PBE/bin/PlusMathTest" "--xml-file=C:/D/PBE/PlusLibData/TestImages/PlusMathTestData.xml")
add_test(AccurateTimerTest "C:/D/PBE/bin/AccurateTimerTest" "--testTimeSec=10" "--averageIntendedDelaySec=0.005" "--numberOfThreads=3" "--verbose=3")
set_tests_properties(AccurateTimerTest PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
add_test(vtkTransformRepositoryTest "C:/D/PBE/bin/vtkTransformRepositoryTest" "--verbose=3")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileTrim "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--operation=TRIM" "--first-frame-index=0" "--last-frame-index=5" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileTrim PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" WORKING_DIRECTORY "C:/D/PBE/bin")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileTrim "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--operation=TRIM" "--first-frame-index=0" "--last-frame-index=5" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileTrim PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" WORKING_DIRECTORY "C:/D/PBE/bin")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileTrim "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--operation=TRIM" "--first-frame-index=0" "--last-frame-index=5" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileTrim PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" WORKING_DIRECTORY "C:/D/PBE/bin")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileTrim "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--operation=TRIM" "--first-frame-index=0" "--last-frame-index=5" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileTrim PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING" WORKING_DIRECTORY "C:/D/PBE/bin")
else()
  add_test(EditSequenceFileTrim NOT_AVAILABLE)
endif()
add_test(EditSequenceFileTrimCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha")
set_tests_properties(EditSequenceFileTrimCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileTrim")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileReadWriteNrrd "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/NrrdSample.nrrd" "--output-seq-file=NrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileReadWriteNrrd "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/NrrdSample.nrrd" "--output-seq-file=NrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileReadWriteNrrd "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/NrrdSample.nrrd" "--output-seq-file=NrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileReadWriteNrrd "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/NrrdSample.nrrd" "--output-seq-file=NrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileReadWriteNrrd NOT_AVAILABLE)
endif()
add_test(EditSequenceFileReadWriteNrrdCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/NrrdSample.nrrd" "C:/D/PBE/PlusLibData/TestImages/NrrdSample.nrrd")
set_tests_properties(EditSequenceFileReadWriteNrrdCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileReadWriteNrrd")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileReadWriteColorNrrd "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/ColorNrrdSample.nrrd" "--output-seq-file=ColorNrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteColorNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileReadWriteColorNrrd "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/ColorNrrdSample.nrrd" "--output-seq-file=ColorNrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteColorNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileReadWriteColorNrrd "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/ColorNrrdSample.nrrd" "--output-seq-file=ColorNrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteColorNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileReadWriteColorNrrd "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/ColorNrrdSample.nrrd" "--output-seq-file=ColorNrrdSample.nrrd" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileReadWriteColorNrrd PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileReadWriteColorNrrd NOT_AVAILABLE)
endif()
add_test(EditSequenceFileReadWriteColorNrrdCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/ColorNrrdSample.nrrd" "C:/D/PBE/PlusLibData/TestImages/ColorNrrdSample.nrrd")
set_tests_properties(EditSequenceFileReadWriteColorNrrdCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileReadWriteColorNrrd")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileFillImageRectangle "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--operation=FILL_IMAGE_RECTANGLE" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--fill-gray-level=20" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Anonymized.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileFillImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileFillImageRectangle "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--operation=FILL_IMAGE_RECTANGLE" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--fill-gray-level=20" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Anonymized.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileFillImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileFillImageRectangle "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--operation=FILL_IMAGE_RECTANGLE" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--fill-gray-level=20" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Anonymized.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileFillImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileFillImageRectangle "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--operation=FILL_IMAGE_RECTANGLE" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--fill-gray-level=20" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Anonymized.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileFillImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileFillImageRectangle NOT_AVAILABLE)
endif()
add_test(EditSequenceFileFillImageRectangleCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Anonymized.mha" "C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Anonymized.mha")
set_tests_properties(EditSequenceFileFillImageRectangleCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileFillImageRectangle")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileCropImageRectangle "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--operation=CROP" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_PatientCropped.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileCropImageRectangle "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--operation=CROP" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_PatientCropped.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileCropImageRectangle "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--operation=CROP" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_PatientCropped.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileCropImageRectangle "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--operation=CROP" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_PatientCropped.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangle PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileCropImageRectangle NOT_AVAILABLE)
endif()
add_test(EditSequenceFileCropImageRectangleCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_PatientCropped.mha" "C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_PatientCropped.mha")
set_tests_properties(EditSequenceFileCropImageRectangleCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileCropImageRectangle")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileCropImageRectangleFlipX "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--operation=CROP" "--flipX" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Cropped_FlipX.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangleFlipX PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileCropImageRectangleFlipX "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--operation=CROP" "--flipX" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Cropped_FlipX.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangleFlipX PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileCropImageRectangleFlipX "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--operation=CROP" "--flipX" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Cropped_FlipX.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangleFlipX PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileCropImageRectangleFlipX "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--operation=CROP" "--flipX" "--rect-origin" "52" "25" "--rect-size" "260" "25" "--source-seq-file=C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed.mha" "--output-seq-file=SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Cropped_FlipX.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileCropImageRectangleFlipX PROPERTIES  DEPENDS "EditSequenceFileTrim" FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileCropImageRectangleFlipX NOT_AVAILABLE)
endif()
add_test(EditSequenceFileCropImageRectangleFlipXCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Cropped_FlipX.mha" "C:/D/PBE/PlusLibData/TestImages/SegmentationTest_BKMedical_RandomStepperMotionData2_Trimmed_Cropped_FlipX.mha")
set_tests_properties(EditSequenceFileCropImageRectangleFlipXCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileCropImageRectangleFlipX")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileRemoveImageData "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUS.mha" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageData PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileRemoveImageData "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUS.mha" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageData PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileRemoveImageData "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUS.mha" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageData PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileRemoveImageData "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUS.mha" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageData PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileRemoveImageData NOT_AVAILABLE)
endif()
add_test(EditSequenceFileRemoveImageDataCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUS.mha" "C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUS.mha")
set_tests_properties(EditSequenceFileRemoveImageDataCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileRemoveImageData")
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(EditSequenceFileRemoveImageDataCompressed "C:/D/PBE/bin/Debug/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUSCompressed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageDataCompressed PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(EditSequenceFileRemoveImageDataCompressed "C:/D/PBE/bin/Release/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUSCompressed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageDataCompressed PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(EditSequenceFileRemoveImageDataCompressed "C:/D/PBE/bin/MinSizeRel/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUSCompressed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageDataCompressed PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(EditSequenceFileRemoveImageDataCompressed "C:/D/PBE/bin/RelWithDebInfo/EditSequenceFile.exe" "--operation=REMOVE_IMAGE_DATA" "--source-seq-file=C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaseline.mha" "--output-seq-file=UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUSCompressed.mha" "--use-compression" "--verbose=3")
  set_tests_properties(EditSequenceFileRemoveImageDataCompressed PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR;WARNING")
else()
  add_test(EditSequenceFileRemoveImageDataCompressed NOT_AVAILABLE)
endif()
add_test(EditSequenceFileRemoveImageDataCompressedCompareToBaselineTest "C:/Program Files/CMake/bin/cmake.exe" "-E" "compare_files" "C:/D/PBE/bin/Release/Output/UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUSCompressed.mha" "C:/D/PBE/PlusLibData/TestImages/UsSimulatorOutputSpinePhantom2CurvilinearBaselineNoUSCompressed.mha")
set_tests_properties(EditSequenceFileRemoveImageDataCompressedCompareToBaselineTest PROPERTIES  DEPENDS "EditSequenceFileRemoveImageDataCompressed")
